[theme]
primaryColor = "#FFFFFF"        # Akzente in Weiß (Monochromer Look)
backgroundColor = "#000000"     # Antigravity Black
secondaryBackgroundColor = "#111111" # Sehr dunkles Grau für Sidebar
textColor = "#FFFFFF"           # Reines Weiß
font = "sans serif"

[server]
runOnSave = true
